---
- name: Créer un utilisateur et un groupe
  hosts: all  

  vars:
    username: mon_utilisateur
    groupname: mon_groupe
    default_password: my_default_password

  tasks:
    - name: Vérifier si le groupe existe
      group_info:
        name: "{{ groupname }}"
      register: group_check
      ignore_errors: yes

    - name: Créer le groupe s'il n'existe pas
      group:
        name: "{{ groupname }}"
      when: group_check is failed  # Si le groupe n'existe pas

    - name: Créer l'utilisateur
      user:
        name: "{{ username }}"
        password: "{{ default_password | password_hash('sha512') }}"
        groups: "{{ groupname }}"
        shell: /bin/bash
        append: yes  # Ajoute l'utilisateur au groupe sans supprimer les groupes existants
        state: present

    - name: Définir l'utilisateur comme utilisateur standard
      become: yes
      user:
        name: "{{ username }}"
        shell: /bin/bash
        append: yes  # Ajoute l'utilisateur au groupe sans supprimer les groupes existants
        groups: "{{ groupname }}"
