---
- name: Collect User and Group Information
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get Users
      shell: getent passwd
      register: users_output
      changed_when: false

    - name: Get Groups
      shell: getent group
      register: groups_output
      changed_when: false

    - name: Print User Information
      debug:
        var: users_output.stdout_lines

    - name: Print Group Information
      debug:
        var: groups_output.stdout_lines
