---
- name: Collect User and Group Information
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get Users
      shell: getent passwd
      register: users_output
      changed_when: false

    - name: Get Groups
      shell: getent group
      register: groups_output
      changed_when: false

    - name: Format User Information
      set_fact:
        user_list: "{{ users_output.stdout_lines | map('regex_replace', '^([^:]+):.*', '\\1') | list }}"

    - name: Format Group Information
      set_fact:
        group_list: "{{ groups_output.stdout_lines | map('regex_replace', '^([^:]+):.*', '\\1') | list }}"

    - name: Print Information
      debug:
        msg: |
          Users:
          {% for user in user_list %}
            - {{ user }}
          {% endfor %}

          Groups:
          {% for group in group_list %}
            - {{ group }}
          {% endfor %}
