- hosts: "{{ target_hosts }}"
  become: yes
  become_user: "{{ ansible_user }}"
  vars:
    firewall_ports_tcp: "{{ lookup('env','FIREWALL_PORTS_TCP') | split(',') }}"
    firewall_ports_udp: "{{ lookup('env','FIREWALL_PORTS_UDP') | split(',') }}"
  tasks:
    - name: Afficher les ports TCP
      debug:
        msg: "Ports TCP à ouvrir : {{ firewall_ports_tcp }}"
    
    - name: Afficher les ports UDP
      debug:
        msg: "Ports UDP à ouvrir : {{ firewall_ports_udp }}"
    
    - name: Installer ufw
      apt:
        name: ufw
        state: present

    - name: Activer ufw
      ufw:
        state: enabled

    - name: Ouvrir les ports TCP nécessaires dans le pare-feu UFW
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop: "{{ firewall_ports_tcp }}"
    
    - name: Ouvrir les ports UDP nécessaires dans le pare-feu UFW
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: udp
      loop: "{{ firewall_ports_udp }}"
