---
- hosts: AWS
  vars_prompt:
    - name: write_file
      prompt: "Voulez-vous écrire un fichier random dans /tmp/random_file.txt ? (y/n)"
      private: false

  tasks:
    - name: Demande interactive
      ansible.builtin.debug:
        msg: 'Votre choix : {{ write_file }}'

    - name: Écriture du fichier random
      ansible.builtin.command: echo "{{ lookup('password', '/dev/urandom chars=ascii_letters length=10') }}" > "/tmp/random_file.txt"
      when: write_file | lower == 'y'
