---
- hosts: AWS
  vars_prompt:
    - name: "age"
      private: no
      prompt: "Enter your age"
    - name: "myname"
      private: no
      prompt: "Enter your name"
    - name: "compname"
      private: no
      prompt: "Enter your company name"

  tasks:
    - name: "Using Debug module"
      debug:
        msg: "Name - {{ myname }} Age - {{ age }} CompanyName: {{ compname }} HOSTNAME - {{ inventory_hostname }}"
    - debug:
        var: find_output
