- name: MAJ
  hosts: AWS
  become_user: ec2-user
  tasks:
    - name: Exécuter la mise à jour des paquets
      yum:
        name: '*'
        state: latest
        exclude:
          - kernel
          - wireguard
          - libc
          - python
      register: yum_output
    
    - name: Afficher la liste des paquets non mis à jour
      debug:
        msg: "{{ yum_output.package_list | default('Aucun paquet non mis à jour', true) }}"
