- name: MAJ
  hosts: AWS
  become_user: ec2-user
  tasks:
    - name: yum_update
      yum:
        name: '*'
        state: latest
      register: yum_output
    
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "Aucun paquet à mettre à jour"
      when: not yum_output.changed
      tags: no_packages_updated
    
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "{{ yum_output | default('Aucun paquet à mettre à jour', true) }}"
      when: yum_output.changed
      tags: packages_updated

    - name: Redémarrer les services nécessaires
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ ansible_services }}"
      when: item not in excluded_services
      ignore_errors: true

  vars:
    excluded_services:
      - service1
      - service2
      # Ajoute d'autres services à exclure au besoin
