- name: MAJ
  hosts: AWS
  become_user: ec2-user
  tasks:
    - name: yum_update
      yum:
        name: '*'
        state: latest
      register: yum_output
    
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "Aucun paquet à mettre à jour"
      when: not yum_output.changed
      tags: no_packages_updated
    
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "{{ yum_output.results | map(attribute='item') | list }}"
      when: yum_output.changed
      tags: packages_updated
