- name: MAJ
  hosts: AWS
  become_user: ec2-user
  tasks:
    - name: yum_update
      yum:
        name: '*'
        state: latest
      register: yum_output
    
    - name: Afficher le statut des mises à jour
      debug:
        var: yum_output.changed
      
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "{{ yum_output | default('Aucun paquet à mettre à jour', true) }}"
      when: yum_output.changed
