- name: MAJ
  hosts: AWS
  become_user: ec2-user
  tasks:
    - name: Collecter les faits sur les services
      service_facts:

    - name: yum_update
      yum:
        name: '*'
        state: latest
      register: yum_output

    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "{% if not yum_output.changed %}Aucun paquet à mettre à jour{% else %}{{ yum_output | default('Aucun paquet à mettre à jour', true) }}{% endif %}"
      tags:
        - no_packages_updated
        - packages_updated

    - name: Redémarrer les services nécessaires
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ ansible_facts.services | map(attribute='name') | list }}"
      when: item not in excluded_services
      ignore_errors: true

  vars:
    excluded_services:
      - service1
      - service2
      # Ajoute d'autres services à exclure au besoin
