- name: MAJ YUM
  hosts: "{{ ansible_host }}"
  become_user: "{{ ansible_user }}"
  vars:
    services_to_exclude: "{{ exclude_services }}"
  tasks:
    - name: yum_update
      yum:
        name: '*'
        state: latest
      register: yum_output
    
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "Aucun paquet à mettre à jour"
      when: not yum_output.changed
      tags: no_packages_updated
    
    - name: Afficher la liste des paquets mis à jour
      debug:
        msg: "{{ yum_output | default('Aucun paquet à mettre à jour', true) }}"
      when: yum_output.changed
      tags: packages_updated

    - name: Vérifier les services à redémarrer
      shell: needs-restarting -s
      register: services_to_restart
      when: yum_output.changed
      tags: check_services_to_restart

    - name: Redémarrer les services
      service:
        name: "{{ item }}"
        state: restarted
      with_items: "{{ services_to_restart.stdout_lines }}"
      when: yum_output.changed and item not in services_to_exclude
      tags: services_restarted
