- name: Run tasks locally
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  vars:
    preparsrv_path: "{{ playbook_dir }}/../preparationServer/files/staticVariables.json.j2"
    preparesrvok_path: "/tmp/.privatevar/{{ semaphore_vars.task_details.id }}/staticVariables.json"
  tasks:
    - name: Set GitHub token
      set_fact:
        github_token: "{{ lookup('env', 'github_token') }}"

    - name: Set MongoDB URL
      set_fact:
        mongodb_url: "{{ lookup('env', 'mongodb_url') }}"

    - name: Set NPM token
      set_fact:
        npm_token: "{{ lookup('env', 'npm_token') }}"

    - name: Set Cloudflare token
      set_fact:
        cloudflare_token: "{{ lookup('env', 'cloudflare_token') }}"

    - name: Set Telegram token
      set_fact:
        telegram_token: "{{ lookup('env', 'telegram_token') }}"

    - name: Set S3 access key read
      set_fact:
        s3_access_key_read: "{{ lookup('env', 's3_access_key_read') }}"
        
    - name: Set S3 secret key read
      set_fact:
        s3_secret_key_read: "{{ lookup('env', 's3_secret_key_read') }}"

    - name: Set S3 access key write
      set_fact:
        s3_access_key_write: "{{ lookup('env', 's3_access_key_write') }}"
        
    - name: Set S3 secret key write
      set_fact:
        s3_secret_key_write: "{{ lookup('env', 's3_secret_key_write') }}"

    - name: Check if file var exists
      ansible.builtin.stat:
        path: "{{ preparesrvok_path }}"
      register: file_var

    - name: Ensures work tree directories exist
      ansible.builtin.file:
        path: "{{ preparesrvok_path | dirname }}"
        state: directory
      when: not file_var.stat.exists

    - name: Generate ansible variable from file
      ansible.builtin.template:
        src: "{{ preparsrv_path }}"
        dest: "{{ preparesrvok_path }}"
      when: not file_var.stat.exists
